import type{SupabaseClient}from"@supabase/supabase-js";import type{Database}from"@/integrations/supabase/types";import{assessFatigueDecoupling}from"./endurance-fatigue-decoupling.engine";import{buildPostRunBrief}from"./endurance-post-run.engine";import{loadDigitalAthleteState}from"./digital-athlete.service";
export async function loadLatestPostRunBrief(supabase:SupabaseClient<Database>,userId:string){
 const{data:run,error}=await supabase.from("workout_sessions").select("id,distance_meters,duration_seconds,endurance_session_intent,endurance_plan_session_key,endurance_match_source,endurance_match_score").eq("user_id",userId).eq("activity_kind","run").not("finished_at","is",null).order("started_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(!run||run.distance_meters===null||run.duration_seconds===null)return{status:"none" as const};
 const{data:splits,error:splitError}=await supabase.from("endurance_run_splits").select("split_index,distance_meters,duration_seconds,average_heart_rate_bpm,cadence_spm").eq("user_id",userId).eq("workout_session_id",run.id).order("split_index");if(splitError)throw splitError;
 const fatigue=assessFatigueDecoupling((splits??[]).map(x=>({index:x.split_index,distanceMeters:Number(x.distance_meters),durationSeconds:Number(x.duration_seconds),averageHeartRateBpm:x.average_heart_rate_bpm,cadenceSpm:x.cadence_spm===null?null:Number(x.cadence_spm)})));
 const athlete=await loadDigitalAthleteState(supabase,userId);const score=athlete.recovery.latestReadinessScore,band=score===null?"unknown":score<55?"low":score<80?"moderate":"high";
 const match=run.endurance_session_intent&&run.endurance_plan_session_key&&run.endurance_match_score!==null?{status:"confident" as const,plannedIndex:0,plannedSessionKey:run.endurance_plan_session_key,score:Number(run.endurance_match_score),reason:"distance_and_effort_align" as const}:null;
 return{status:"ready" as const,workoutSessionId:run.id,brief:buildPostRunBrief({distanceMeters:Number(run.distance_meters),durationSeconds:Number(run.duration_seconds),match,fatigue,readinessBand:band}),fatigue,matchSource:run.endurance_match_source,sessionIntent:run.endurance_session_intent};
}
