/** A deliberately limited positive-match dictionary, not an allergen detector.
 * '*' marks a word stem. Matches never establish that a product is free from anything.
 * Main coverage: English and Lithuanian; a few additional common names are included.
 */
export const FOOD_TERMS = {
  milk: [
    "milk",
    "dairy",
    "whey",
    "casein*",
    "butter",
    "cheese",
    "yogurt",
    "yoghurt",
    "cream",
    "kefir",
    "pien*",
    "išrūg*",
    "kazein*",
    "sviest*",
    "sūris",
    "sūrio",
    "sūrių",
    "varšk*",
    "jogurt*",
    "grietin*",
    "молок*",
    "сыр",
    "творог*",
  ],
  eggs: ["egg", "eggs", "kiaušin*", "яйц*"],
  peanuts: ["peanut*", "groundnut*", "žemės riešut*", "арахис*"],
  nuts: [
    "tree nuts",
    "nuts",
    "almond*",
    "cashew*",
    "walnut*",
    "hazelnut*",
    "pistachio*",
    "pecan*",
    "macadamia*",
    "brazil nut*",
    "riešut*",
    "migdol*",
    "anakard*",
    "lazdyn*",
    "pistacij*",
    "орех*",
    "миндал*",
    "кешью",
  ],
  soy: ["soy", "soya", "soybean*", "tofu", "tempeh", "edamame", "miso", "soj*", "соя", "соев*"],
  fish: [
    "fish",
    "salmon",
    "tuna",
    "cod",
    "haddock",
    "sardine*",
    "anchov*",
    "žuv*",
    "lašiš*",
    "tunas",
    "tuno",
    "menk*",
    "рыб*",
    "лосос*",
    "тунец",
  ],
  crustaceans: [
    "crustacean*",
    "shellfish",
    "shrimp",
    "prawn*",
    "crab",
    "lobster",
    "vėžiag*",
    "krevet*",
    "krab*",
    "omar*",
    "кревет*",
  ],
  molluscs: [
    "mollusc*",
    "shellfish",
    "mussel*",
    "oyster*",
    "squid",
    "octopus",
    "clam",
    "clams",
    "moliusk*",
    "midij*",
    "austrė*",
    "kalmar*",
    "aštuonkoj*",
  ],
  gluten: [
    "gluten",
    "wheat",
    "barley",
    "rye",
    "spelt",
    "seitan",
    "bulgur",
    "couscous",
    "oats",
    "oat",
    "bread",
    "pasta",
    "kviet*",
    "glitim*",
    "rugiai",
    "rugių",
    "miež*",
    "spelt*",
    "aviž*",
    "duon*",
    "makaron*",
    "пшениц*",
    "рожь",
    "ячмень",
    "глютен",
  ],
  sesame: ["sesame", "tahini", "sezam*", "кунжут*"],
  celery: ["celery", "celeriac", "salier*", "сельдер*"],
  mustard: ["mustard", "garstyč*", "горчиц*"],
  lupin: ["lupin*", "lubin*", "люпин*"],
  sulphites: [
    "sulphite*",
    "sulfite*",
    "sulphur dioxide",
    "sulfur dioxide",
    "sulfit*",
    "sieros dioksid*",
    "сульфит*",
  ],
} as const;
export type KnownFoodGroup = keyof typeof FOOD_TERMS;
export const MEAT_TERMS = [
  "meat",
  "chicken",
  "turkey",
  "beef",
  "pork",
  "bacon",
  "ham",
  "lamb",
  "gelatin*",
  "mėsa",
  "mėsos",
  "vištien*",
  "kalakut*",
  "jautien*",
  "kiaulien*",
  "avien*",
  "želatin*",
  "куриц*",
  "говядин*",
  "свинин*",
  "мяс*",
];
export const HONEY_TERMS = ["honey", "medus", "medaus", "мёд"];
