import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { copy as landingCopy } from "@/components/FutureLabLanding";
import { SHARE_CARD_HEIGHT, SHARE_CARD_PATH, SHARE_CARD_URL, SHARE_CARD_WIDTH } from "./site";

/**
 * What a shared gyms.life link promises, against the page it opens.
 *
 * The head said "GYMS.LIFE — Your personal Future Lab" and "Your training. Your
 * Digital Twin. Your next step." long after the hero was rewritten to name 175
 * exercises, sets that survive a dead signal and free-while-in-beta. Every
 * shared link, search result and chat preview carried the abstract line the
 * page itself had stopped making, and nothing in the build compared the two —
 * the same shape as the exercise pages that said "video" for 165 movements that
 * have none.
 *
 * And there was no image at all, which is why `twitter:card` was the small
 * `summary`. There is one now, so the card type has to stay honest about it in
 * both directions: an image that disappears must fail here rather than ship a
 * broken preview.
 */

const INDEX = path.resolve("src/routes/index.tsx");
const ROOT = path.resolve("src/routes/__root.tsx");
const CARD = path.resolve(`public${SHARE_CARD_PATH}`);
const source = () => readFileSync(INDEX, "utf8");

/** Width and height straight out of the PNG's IHDR, so a resize cannot pass. */
function pngSize(file: string): { width: number; height: number } {
  const bytes = readFileSync(file);
  expect(bytes.subarray(0, 8).toString("hex"), "is a PNG").toBe("89504e470d0a1a0a");
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

describe("the share card", () => {
  it("exists, at the size every crawler expects", () => {
    expect(existsSync(CARD), `${SHARE_CARD_PATH} is generated by npm run build:share-card`).toBe(
      true,
    );
    expect(pngSize(CARD)).toEqual({ width: SHARE_CARD_WIDTH, height: SHARE_CARD_HEIGHT });
    // Large enough to be a real render, small enough that a shared link is not
    // a download. Facebook and X both reject images over 5 MB.
    const bytes = statSync(CARD).size;
    expect(bytes).toBeGreaterThan(20_000);
    expect(bytes).toBeLessThan(2_000_000);
  });

  it("is pointed at by an absolute URL, because a relative one is ignored", () => {
    expect(SHARE_CARD_URL).toMatch(/^https:\/\//);
    const head = source();
    expect(head).toMatch(/property: "og:image"/);
    expect(head).toMatch(/name: "twitter:image"/);
  });

  it("claims the large card only because the image is really there", () => {
    // The pair, in both directions. The root deliberately defaults to the small
    // card; a route may upgrade only if it also sets an image.
    expect(source()).toMatch(/content: "summary_large_image"/);
    expect(source()).toMatch(/property: "og:image"/);
    expect(readFileSync(ROOT, "utf8")).toMatch(/name: "twitter:card", content: "summary"/);
  });
});

describe("what the head promises", () => {
  it("is the landing page's own words, not a second copy of them", () => {
    // The whole point. If these are ever retyped instead of derived, the two
    // can drift again, which is how the old claim survived the rewrite.
    expect(source()).toMatch(/landingCopy\.en/);
    expect(source()).toMatch(/content: hero\.intro/);
  });

  it("describes the page a visitor actually lands on", () => {
    // Read the strings rather than the expressions: this is what a crawler gets.
    const hero = landingCopy.en;
    const description = hero.intro;
    expect(description).toMatch(/175/);
    expect(description).toMatch(/beta/i);
    // The claims the rewritten page makes, and the abstract one it dropped.
    expect(description).not.toMatch(/Your next step\.$/);
    expect(`${hero.title} ${hero.accent}`).toBe("Train on the record. Not on a guess.");
  });

  it("no longer carries the line the page stopped making", () => {
    // Scoped to the emitted `meta` array rather than the file, and that is not
    // a convenience: the first version read the whole source and failed on the
    // doc comment above, which quotes the old strings in order to explain them.
    // A scan for a claim has to look where claims are made.
    const head = source();
    const open = head.indexOf("meta: [");
    const close = head.indexOf("],", open);
    expect(open, "the head still emits a meta array").toBeGreaterThan(0);
    expect(close).toBeGreaterThan(open);
    const meta = head.slice(open, close);
    expect(meta).toMatch(/og:title/);
    expect(meta).not.toMatch(/Your personal Future Lab/);
    expect(meta).not.toMatch(/Your training\. Your Digital Twin\. Your next step\./);
  });
});
