/**
 * The canonical origin, and the image a shared link shows.
 *
 * Open Graph wants absolute URLs — a relative `og:image` is ignored by every
 * crawler that reads it — so the origin has to be written down somewhere, and
 * it was written down in two places that could drift apart.
 *
 * `share-card.png` is generated by `npm run build:share-card` from the landing
 * hero's own words and the palette in `src/styles.css`. It is a claim made
 * before anyone reaches the page, which is the kind AGENTS.md says nobody
 * rechecks, so `share-card.test.ts` rechecks it.
 */

export const SITE_URL = "https://gyms.life";

/** Path under `public/`, and the absolute URL crawlers are given. */
export const SHARE_CARD_PATH = "/share-card.png";
export const SHARE_CARD_URL = `${SITE_URL}${SHARE_CARD_PATH}`;

/** What the card renders, so a crawler reading alt text gets the same claim. */
export const SHARE_CARD_WIDTH = 1200;
export const SHARE_CARD_HEIGHT = 630;
