-- gyms.life — exercise catalogue seed
--
-- Reference data, not user data: the public exercise library the app browses
-- and builds programmes from. Extracted verbatim from the two migrations that
-- populate it, so this file and production carry the same rows.
--
-- Apply after supabase/schema.sql.

-- from 20260823202828_5e2fb3a5-1aff-428e-9e98-29c9e9c2e460.sql
INSERT INTO public.exercises (slug, name_lt, name_en, muscle_group, equipment, location, difficulty, instructions_lt, instructions_en, mistakes_lt, mistakes_en, video_key) VALUES
('squat','Pritūpimai su štanga','Barbell Back Squat','legs','barbell','gym','intermediate','Štanga ant trapecinių raumenų, pėdos pečių plotyje. Leiskitės kontroliuojamai, kol šlaunys bus lygiagrečios grindims, kelius kreipkite pėdų kryptimi, nugarą laikykite tiesią.','Bar on upper back, feet shoulder-width. Descend under control until thighs are parallel, knees tracking over toes, spine neutral.','Kelių kritimas į vidų, kulnų atsikėlimas, apvali nugara.','Knees caving in, heels rising, rounded back.','squat'),
('deadlift','Mirties trauka','Deadlift','back','barbell','gym','advanced','Štanga prie blauzdų, nugara tiesi, pečiai virš štangos. Kelkite stumdami grindis kojomis ir tiesdami klubus.','Bar over midfoot, neutral spine, shoulders above bar. Drive through the floor and extend hips.','Apvali juosmens sritis, štanga toli nuo kūno.','Rounded lower back, bar drifting away from body.','deadlift'),
('bench-press','Spaudimas gulint','Barbell Bench Press','chest','barbell','gym','intermediate','Menčių suvedimas, pėdos ant grindų. Nuleiskite štangą prie krūtinės vidurio, spauskite iki visiško alkūnių ištiesimo.','Retract shoulder blades, feet planted. Lower bar to mid-chest and press to full lockout.','Alkūnės išskėstos 90°, atsikeliantis dubuo.','Elbows flared to 90°, hips lifting off the bench.','bench-press'),
('pull-up','Prisitraukimai','Pull-Up','back','bodyweight','both','advanced','Platus laikymas, pečiai nuleisti. Traukite alkūnes žemyn, kol smakras virš skersinio.','Wide grip, shoulders down. Pull elbows to ribs until chin clears the bar.','Supimasis, nepilna amplitudė.','Swinging, partial range of motion.','pull-up'),
('push-up','Atsispaudimai','Push-Up','chest','bodyweight','home','beginner','Kūnas viena linija, alkūnės ~45° kampu. Leiskitės, kol krūtinė beveik liečia grindis.','Body in one line, elbows at ~45°. Lower until chest nearly touches the floor.','Nukarę klubai, galvos kišimas į priekį.','Sagging hips, head poking forward.','push-up'),
('plank','Lenta','Plank','core','bodyweight','home','beginner','Alkūnės po pečiais, pilvo ir sėdmenų raumenys įtempti, kūnas tiesus.','Elbows under shoulders, brace abs and glutes, body straight.','Pakeltas arba nukaręs dubuo.','Hips too high or sagging.','plank'),
('lunge','Išpuoliai','Walking Lunge','legs','bodyweight','both','beginner','Ženkite plačiai į priekį, nuleiskite užpakalinį kelį beveik iki grindų, liemuo tiesus.','Step forward, lower the back knee toward the floor, torso upright.','Per trumpas žingsnis, kelio kritimas į vidų.','Step too short, knee caving inward.','lunge'),
('overhead-press','Spaudimas virš galvos','Overhead Press','shoulders','barbell','gym','intermediate','Štanga ties raktikauliais, sėdmenys ir pilvas įtempti. Spauskite tiesiai virš galvos.','Bar at clavicles, glutes and abs braced. Press straight overhead.','Per didelis nugaros lenkimas.','Excessive lower-back arch.','overhead-press'),
('barbell-row','Irklavimas su štanga','Barbell Row','back','barbell','gym','intermediate','Liemuo ~45°, nugara tiesi. Traukite štangą prie pilvo, mentes suveskite.','Torso at ~45°, neutral spine. Row the bar to the belly, squeeze shoulder blades.','Liemens kilnojimas, trūkčiojimas.','Using momentum, torso rising.','barbell-row'),
('romanian-deadlift','Rumuniška trauka','Romanian Deadlift','legs','barbell','gym','intermediate','Kojos beveik tiesios, klubus stumkite atgal, štanga slysta palei šlaunis.','Soft knees, push hips back, bar slides along thighs.','Nugaros apvalinimas, tūpimas vietoj klubų lenkimo.','Rounding back, squatting instead of hinging.','romanian-deadlift'),
('goblet-squat','Pritūpimai su svarmeniu','Goblet Squat','legs','dumbbell','both','beginner','Svarmenį laikykite prie krūtinės, tūpkite giliai, liemuo tiesus.','Hold the weight at the chest, squat deep, torso upright.','Priekinis palinkimas.','Leaning too far forward.','goblet-squat'),
('dumbbell-press','Spaudimas su hanteliais','Dumbbell Bench Press','chest','dumbbell','both','beginner','Hanteliai virš krūtinės, nuleiskite iki krūtinės lygio, spauskite kartu.','Dumbbells above chest, lower to chest level, press together.','Per gilus nuleidimas su per dideliu svoriu.','Overstretching with too heavy weight.','dumbbell-press'),
('lat-pulldown','Viršutinės sklendės trauka','Lat Pulldown','back','machine','gym','beginner','Traukite rankeną prie krūtinės, alkūnės žemyn, liemuo beveik tiesus.','Pull the bar to the chest, elbows down, torso nearly upright.','Atsilošimas visu kūnu.','Leaning back excessively.','lat-pulldown'),
('leg-press','Kojų spaudimas','Leg Press','legs','machine','gym','beginner','Pėdos platformos viduryje, leiskite iki 90° kelių kampo.','Feet mid-platform, lower to about 90° knee bend.','Kelių fiksavimas trūkčiojant, juosmens atsikėlimas.','Locking knees harshly, lower back lifting.','leg-press'),
('burpee','Burpee','Burpee','fullbody','bodyweight','home','intermediate','Iš stovėsenos į atsispaudimą, tada šuolis aukštyn. Judesys sklandus ir ritmiškas.','From standing to a push-up, then jump up. Keep the rhythm smooth.','Nukarę klubai atsispaudime.','Sagging hips in the push-up.','burpee'),
('mountain-climber','Alpinistas','Mountain Climber','core','bodyweight','home','beginner','Lentos padėtis, greitai keiskite kelius prie krūtinės.','Plank position, drive knees to chest alternately at pace.','Kilnojami klubai.','Bouncing hips.','mountain-climber'),
('glute-bridge','Sėdmenų tiltelis','Glute Bridge','glutes','bodyweight','home','beginner','Gulint kelkite dubenį, viršuje suspauskite sėdmenis.','Lying down, lift hips and squeeze glutes at the top.','Juosmens lenkimas vietoj sėdmenų darbo.','Arching the lower back instead of using glutes.','glute-bridge'),
('hip-thrust','Klubų stūmimas','Barbell Hip Thrust','glutes','barbell','gym','intermediate','Pečiai ant suolo, štanga ant klubų, kelkite iki pilno klubų ištiesimo.','Shoulders on bench, bar over hips, drive to full hip extension.','Per didelis juosmens lenkimas viršuje.','Overarching at the top.','hip-thrust'),
('bicep-curl','Bicepso lenkimas','Dumbbell Biceps Curl','arms','dumbbell','both','beginner','Alkūnės prie liemens, kelkite kontroliuojamai, leiskite lėtai.','Elbows at your sides, curl under control, lower slowly.','Kūno supimas.','Swinging the body.','bicep-curl'),
('tricep-dip','Tricepso atsispaudimai','Triceps Dip','arms','bodyweight','both','beginner','Rankos ant suolo/lygiagrečių, leiskitės iki 90° alkūnių kampo.','Hands on bench or bars, lower to 90° elbow bend.','Pečių kėlimas prie ausų.','Shrugging shoulders up.','tricep-dip'),
('face-pull','Trauka prie veido','Face Pull','shoulders','cable','gym','beginner','Traukite virvę prie veido, alkūnės aukštai, mentes suveskite.','Pull the rope to your face, elbows high, squeeze the rear delts.','Per didelis svoris, liemens atsilošimas.','Too heavy, leaning back.','face-pull'),
('russian-twist','Rusiški sukimai','Russian Twist','core','bodyweight','home','beginner','Sėdint atsilošite, sukite liemenį iš šono į šoną.','Sit leaning back, rotate the torso side to side.','Sukimas tik rankomis.','Moving only the arms.','russian-twist'),
('jump-rope','Šokdynė','Jump Rope','cardio','other','home','beginner','Nedideli šuoliukai ant pirštų galų, riešai sukasi, alkūnės prie kūno.','Small bounces on the balls of your feet, wrists rotate, elbows in.','Per aukšti šuoliai.','Jumping too high.','jump-rope'),
('kettlebell-swing','Svarsčio mostai','Kettlebell Swing','fullbody','kettlebell','both','intermediate','Klubų lenkimas, sprogstamas klubų ištiesimas, svarstis skrieja iki krūtinės.','Hip hinge, explosive hip extension, bell floats to chest height.','Tūpimas vietoj klubų lenkimo, rankų traukimas.','Squatting instead of hinging, pulling with arms.','kettlebell-swing');

-- from 20260827210844_20c2d82b-22a7-44bd-b780-adf37a700471.sql
insert into public.exercises (slug, name_lt, name_en, muscle_group, equipment, location, difficulty, instructions_lt, instructions_en, mistakes_lt, mistakes_en)
select v.slug, v.lt, v.en, v.mg, v.eq, v.loc, v.diff,
  'Pasiruošk „' || v.lt || '“: stabili padėtis, įtemptas liemuo. Leisk svorį kontroliuojamai 2–3 sek., dirbk pilna amplitude ir kvėpuok ritmiškai.',
  'Set up for the ' || v.en || ' with a stable stance and braced core. Lower under control for 2-3 seconds, work through the full range and keep your breathing rhythmic.',
  'Per didelis svoris, skubėjimas, per maža amplitudė ir prarasta liemens ar pečių padėtis.',
  'Too much load, rushed reps, a shortened range of motion and losing core or shoulder position.'
from (values
  ('front-squat','Priekinis pritūpimas','Front Squat','legs','barbell','gym','advanced'),
  ('box-squat','Pritūpimas ant dėžės','Box Squat','legs','barbell','gym','intermediate'),
  ('pause-squat','Pritūpimas su pauze','Paused Squat','legs','barbell','gym','intermediate'),
  ('zercher-squat','Zercher pritūpimas','Zercher Squat','legs','barbell','gym','advanced'),
  ('barbell-lunge','Išpuolis su štanga','Barbell Lunge','legs','barbell','gym','intermediate'),
  ('good-morning','Labas rytas','Good Morning','legs','barbell','gym','advanced'),
  ('barbell-step-up','Užlipimas su štanga','Barbell Step-Up','legs','barbell','gym','intermediate'),
  ('barbell-calf-raise','Blauzdų kėlimas su štanga','Barbell Calf Raise','legs','barbell','gym','beginner'),
  ('sumo-deadlift','Sumo mirties trauka','Sumo Deadlift','legs','barbell','gym','advanced'),
  ('db-bulgarian-split-squat','Bulgariškas pritūpimas su hanteliais','Dumbbell Bulgarian Split Squat','legs','dumbbell','both','intermediate'),
  ('db-step-up','Užlipimas su hanteliais','Dumbbell Step-Up','legs','dumbbell','both','beginner'),
  ('db-romanian-deadlift','Rumuniška trauka su hanteliais','Dumbbell Romanian Deadlift','legs','dumbbell','both','beginner'),
  ('db-sumo-squat','Sumo pritūpimas su hanteliu','Dumbbell Sumo Squat','legs','dumbbell','both','beginner'),
  ('db-walking-lunge','Einamieji išpuoliai su hanteliais','Dumbbell Walking Lunge','legs','dumbbell','both','intermediate'),
  ('db-calf-raise','Blauzdų kėlimas su hanteliais','Dumbbell Calf Raise','legs','dumbbell','both','beginner'),
  ('leg-extension','Kojų tiesimas treniruoklyje','Leg Extension','legs','machine','gym','beginner'),
  ('leg-curl','Kojų lenkimas treniruoklyje','Leg Curl','legs','machine','gym','beginner'),
  ('hack-squat','Hack pritūpimas','Hack Squat','legs','machine','gym','intermediate'),
  ('smith-squat','Pritūpimas Smith treniruoklyje','Smith Machine Squat','legs','machine','gym','beginner'),
  ('seated-calf-raise','Blauzdos sėdint treniruoklyje','Seated Calf Raise','legs','machine','gym','beginner'),
  ('abductor-machine','Šlaunų atitraukimas treniruoklyje','Hip Abductor Machine','legs','machine','gym','beginner'),
  ('adductor-machine','Šlaunų pritraukimas treniruoklyje','Hip Adductor Machine','legs','machine','gym','beginner'),
  ('bodyweight-squat','Pritūpimas be svorio','Bodyweight Squat','legs','bodyweight','home','beginner'),
  ('jump-squat','Šuoliukas iš pritūpimo','Jump Squat','legs','bodyweight','home','intermediate'),
  ('pistol-squat','Pistoletas','Pistol Squat','legs','bodyweight','home','advanced'),
  ('wall-sit','Sėdėjimas prie sienos','Wall Sit','legs','bodyweight','home','beginner'),
  ('reverse-lunge','Išpuolis atgal','Reverse Lunge','legs','bodyweight','home','beginner'),
  ('cossack-squat','Kazokiškas pritūpimas','Cossack Squat','legs','bodyweight','home','intermediate'),
  ('calf-raise','Stovimas blauzdų kėlimas','Standing Calf Raise','legs','bodyweight','home','beginner'),
  ('band-squat','Pritūpimas su guma','Band Squat','legs','band','home','beginner'),
  ('band-lateral-walk','Ėjimas į šoną su guma','Band Lateral Walk','glutes','band','home','beginner'),
  ('band-leg-curl','Kojų lenkimas su guma','Band Leg Curl','legs','band','home','beginner'),
  ('band-glute-kickback','Kojos spyris atgal su guma','Band Glute Kickback','glutes','band','home','beginner'),
  ('kb-front-rack-squat','Pritūpimas su svarsčiais ant krūtinės','Kettlebell Front Rack Squat','legs','kettlebell','both','intermediate'),
  ('kb-lunge','Išpuolis su svarsčiu','Kettlebell Lunge','legs','kettlebell','both','beginner'),
  ('kb-deadlift','Svarsčio mirties trauka','Kettlebell Deadlift','legs','kettlebell','both','beginner'),
  ('incline-bench-press','Spaudimas nuo įstrižo suolo','Incline Bench Press','chest','barbell','gym','intermediate'),
  ('decline-bench-press','Spaudimas nuo nuožulnaus suolo','Decline Bench Press','chest','barbell','gym','intermediate'),
  ('close-grip-bench-press','Spaudimas siauru griebimu','Close-Grip Bench Press','arms','barbell','gym','intermediate'),
  ('db-incline-press','Įstrižas spaudimas su hanteliais','Incline Dumbbell Press','chest','dumbbell','both','beginner'),
  ('db-fly','Hantelių išskėtimas','Dumbbell Fly','chest','dumbbell','both','beginner'),
  ('db-pullover','Hantelio kėlimas per galvą','Dumbbell Pullover','chest','dumbbell','both','intermediate'),
  ('cable-fly','Kryžminis suvedimas trosuose','Cable Fly','chest','cable','gym','beginner'),
  ('cable-crossover','Kryžminis trosų suvedimas žemyn','Cable Crossover','chest','cable','gym','intermediate'),
  ('pec-deck','Krūtinės suvedimas treniruoklyje','Pec Deck','chest','machine','gym','beginner'),
  ('chest-press-machine','Krūtinės spaudimas treniruoklyje','Chest Press Machine','chest','machine','gym','beginner'),
  ('chest-dip','Atsispaudimas ant lygiagrečių','Chest Dip','chest','pullup_bar','both','intermediate'),
  ('wide-push-up','Platus atsispaudimas','Wide Push-Up','chest','bodyweight','home','beginner'),
  ('diamond-push-up','Deimantinis atsispaudimas','Diamond Push-Up','arms','bodyweight','home','intermediate'),
  ('decline-push-up','Atsispaudimas su pakeltomis kojomis','Decline Push-Up','chest','bodyweight','home','intermediate'),
  ('archer-push-up','Šaulio atsispaudimas','Archer Push-Up','chest','bodyweight','home','advanced'),
  ('band-chest-press','Krūtinės spaudimas su guma','Band Chest Press','chest','band','home','beginner'),
  ('pendlay-row','Pendlay irklavimas','Pendlay Row','back','barbell','gym','advanced'),
  ('t-bar-row','T formos irklavimas','T-Bar Row','back','barbell','gym','intermediate'),
  ('rack-pull','Trauka nuo stovų','Rack Pull','back','barbell','gym','intermediate'),
  ('barbell-shrug','Pečių gūžčiojimas su štanga','Barbell Shrug','back','barbell','gym','beginner'),
  ('one-arm-db-row','Vienos rankos irklavimas su hanteliu','One-Arm Dumbbell Row','back','dumbbell','both','beginner'),
  ('chest-supported-row','Irklavimas gulint ant suolo','Chest-Supported Row','back','dumbbell','gym','beginner'),
  ('db-shrug','Pečių gūžčiojimas su hanteliais','Dumbbell Shrug','back','dumbbell','both','beginner'),
  ('seated-cable-row','Irklavimas trosu sėdint','Seated Cable Row','back','cable','gym','beginner'),
  ('straight-arm-pulldown','Tiesių rankų trauka žemyn','Straight-Arm Pulldown','back','cable','gym','beginner'),
  ('wide-grip-pulldown','Plati trauka prie krūtinės','Wide-Grip Lat Pulldown','back','machine','gym','beginner'),
  ('close-grip-pulldown','Siaura trauka prie krūtinės','Close-Grip Pulldown','back','machine','gym','beginner'),
  ('machine-row','Irklavimas treniruoklyje','Machine Row','back','machine','gym','beginner'),
  ('hyperextension','Nugaros tiesimas','Back Extension','back','machine','gym','beginner'),
  ('chin-up','Prisitraukimas atvirkštiniu griebimu','Chin-Up','back','pullup_bar','both','intermediate'),
  ('neutral-grip-pull-up','Prisitraukimas neutraliu griebimu','Neutral-Grip Pull-Up','back','pullup_bar','both','intermediate'),
  ('inverted-row','Australiškas prisitraukimas','Inverted Row','back','pullup_bar','both','beginner'),
  ('dead-hang','Kabėjimas ant skersinio','Dead Hang','back','pullup_bar','both','beginner'),
  ('band-pulldown','Trauka žemyn su guma','Band Pulldown','back','band','home','beginner'),
  ('superman','Supermenas','Superman','back','bodyweight','home','beginner'),
  ('db-shoulder-press','Pečių spaudimas su hanteliais','Dumbbell Shoulder Press','shoulders','dumbbell','both','beginner'),
  ('arnold-press','Arnoldo spaudimas','Arnold Press','shoulders','dumbbell','both','intermediate'),
  ('lateral-raise','Rankų kėlimas į šonus','Lateral Raise','shoulders','dumbbell','both','beginner'),
  ('front-raise','Rankų kėlimas į priekį','Front Raise','shoulders','dumbbell','both','beginner'),
  ('rear-delt-fly','Užpakalinių deltų išskėtimas','Rear Delt Fly','shoulders','dumbbell','both','beginner'),
  ('cable-lateral-raise','Kėlimas į šoną trosu','Cable Lateral Raise','shoulders','cable','gym','intermediate'),
  ('upright-row','Trauka prie smakro','Upright Row','shoulders','barbell','gym','intermediate'),
  ('landmine-press','Landmine spaudimas','Landmine Press','shoulders','barbell','gym','intermediate'),
  ('shoulder-press-machine','Pečių spaudimas treniruoklyje','Shoulder Press Machine','shoulders','machine','gym','beginner'),
  ('band-pull-apart','Gumos ištempimas prieš krūtinę','Band Pull-Apart','shoulders','band','home','beginner'),
  ('pike-push-up','Atsispaudimas kampu','Pike Push-Up','shoulders','bodyweight','home','intermediate'),
  ('handstand-hold','Stovėjimas ant rankų prie sienos','Wall Handstand Hold','shoulders','bodyweight','home','advanced'),
  ('barbell-curl','Bicepso lenkimas su štanga','Barbell Curl','arms','barbell','gym','beginner'),
  ('ez-bar-curl','Lenkimas su EZ štanga','EZ-Bar Curl','arms','barbell','gym','beginner'),
  ('skullcrusher','Tricepso tiesimas gulint','Skullcrusher','arms','barbell','gym','intermediate'),
  ('hammer-curl','Plaktukinis lenkimas','Hammer Curl','arms','dumbbell','both','beginner'),
  ('incline-db-curl','Lenkimas ant įstrižo suolo','Incline Dumbbell Curl','arms','dumbbell','gym','intermediate'),
  ('concentration-curl','Koncentruotas lenkimas','Concentration Curl','arms','dumbbell','both','beginner'),
  ('overhead-triceps-extension','Tricepso tiesimas virš galvos','Overhead Triceps Extension','arms','dumbbell','both','beginner'),
  ('wrist-curl','Riešų lenkimas','Wrist Curl','arms','dumbbell','both','beginner'),
  ('preacher-curl','Lenkimas ant pulto','Preacher Curl','arms','machine','gym','beginner'),
  ('cable-curl','Bicepso lenkimas trosu','Cable Curl','arms','cable','gym','beginner'),
  ('triceps-pushdown','Tricepso spaudimas žemyn','Triceps Pushdown','arms','cable','gym','beginner'),
  ('rope-pushdown','Tricepso spaudimas su virve','Rope Pushdown','arms','cable','gym','beginner'),
  ('bench-dip','Atsispaudimas nuo suolo','Bench Dip','arms','bodyweight','home','beginner'),
  ('close-grip-push-up','Siauras atsispaudimas','Close-Grip Push-Up','arms','bodyweight','home','beginner'),
  ('band-curl','Bicepso lenkimas su guma','Band Curl','arms','band','home','beginner'),
  ('band-triceps-extension','Tricepso tiesimas su guma','Band Triceps Extension','arms','band','home','beginner'),
  ('farmers-carry','Ūkininko nešimas','Farmer''s Carry','fullbody','dumbbell','both','beginner'),
  ('hanging-leg-raise','Kojų kėlimas kabant','Hanging Leg Raise','abs','pullup_bar','both','advanced'),
  ('toes-to-bar','Kojų kėlimas prie skersinio','Toes to Bar','abs','pullup_bar','both','advanced'),
  ('captains-chair-raise','Kelių kėlimas kapitono kėdėje','Captain''s Chair Knee Raise','abs','machine','gym','intermediate'),
  ('cable-crunch','Presas trosu klūpant','Cable Crunch','abs','cable','gym','intermediate'),
  ('pallof-press','Pallof spaudimas','Pallof Press','core','cable','gym','intermediate'),
  ('ab-wheel','Ratukas presui','Ab Wheel Rollout','abs','other','home','advanced'),
  ('bicycle-crunch','Dviratukas','Bicycle Crunch','abs','bodyweight','home','beginner'),
  ('side-plank','Šoninė lenta','Side Plank','core','bodyweight','home','beginner'),
  ('hollow-hold','Laivelis','Hollow Hold','core','bodyweight','home','intermediate'),
  ('dead-bug','Negyvas vabalas','Dead Bug','core','bodyweight','home','beginner'),
  ('bird-dog','Paukštis-šuo','Bird Dog','core','bodyweight','home','beginner'),
  ('v-up','V formos kėlimas','V-Up','abs','bodyweight','home','intermediate'),
  ('sit-up','Atsilenkimas','Sit-Up','abs','bodyweight','home','beginner'),
  ('plank-shoulder-tap','Lenta su pečių palietimu','Plank Shoulder Tap','core','bodyweight','home','beginner'),
  ('dragon-flag','Drakono vėliava','Dragon Flag','abs','bodyweight','home','advanced'),
  ('db-hip-thrust','Dubens kėlimas su hanteliu','Dumbbell Hip Thrust','glutes','dumbbell','both','beginner'),
  ('cable-kickback','Kojos spyris trosu','Cable Kickback','glutes','cable','gym','beginner'),
  ('band-hip-thrust','Dubens kėlimas su guma','Band Hip Thrust','glutes','band','home','beginner'),
  ('single-leg-glute-bridge','Tiltelis ant vienos kojos','Single-Leg Glute Bridge','glutes','bodyweight','home','intermediate'),
  ('frog-pump','Varlės kėlimai','Frog Pump','glutes','bodyweight','home','beginner'),
  ('glute-machine','Sėdmenų treniruoklis','Glute Kickback Machine','glutes','machine','gym','beginner'),
  ('rowing-machine','Irklavimo treniruoklis','Rowing Machine','cardio','cardio','gym','beginner'),
  ('assault-bike','Oro dviratis','Assault Bike','cardio','cardio','gym','intermediate'),
  ('treadmill-sprint','Sprintas bėgtakyje','Treadmill Sprint','cardio','cardio','gym','intermediate'),
  ('stair-climber','Laiptų treniruoklis','Stair Climber','cardio','cardio','gym','beginner'),
  ('elliptical','Elipsinis treniruoklis','Elliptical Trainer','cardio','cardio','gym','beginner'),
  ('ski-erg','SkiErg','Ski Erg','cardio','cardio','gym','intermediate'),
  ('box-jump','Šuolis ant dėžės','Box Jump','cardio','bodyweight','both','intermediate'),
  ('high-knees','Aukšti keliai','High Knees','cardio','bodyweight','home','beginner'),
  ('jumping-jack','Šuoliukai su rankomis','Jumping Jack','cardio','bodyweight','home','beginner'),
  ('bear-crawl','Meškos ėjimas','Bear Crawl','fullbody','bodyweight','home','intermediate'),
  ('battle-ropes','Kovos virvės','Battle Ropes','cardio','other','gym','intermediate'),
  ('sled-push','Rogių stūmimas','Sled Push','fullbody','other','gym','intermediate'),
  ('thruster','Trasteris','Thruster','fullbody','barbell','gym','advanced'),
  ('clean-and-press','Ėmimas ir spaudimas','Clean and Press','fullbody','barbell','gym','advanced'),
  ('kb-clean','Svarsčio ėmimas','Kettlebell Clean','fullbody','kettlebell','both','intermediate'),
  ('kb-snatch','Svarsčio trūktelėjimas','Kettlebell Snatch','fullbody','kettlebell','both','advanced'),
  ('kb-turkish-get-up','Turkiškas atsikėlimas','Turkish Get-Up','fullbody','kettlebell','both','advanced'),
  ('trx-row','TRX irklavimas','TRX Row','back','trx','both','beginner'),
  ('trx-push-up','TRX atsispaudimas','TRX Push-Up','chest','trx','both','intermediate'),
  ('trx-fallout','TRX liemens kritimas','TRX Fallout','core','trx','both','advanced'),
  ('trx-pistol','TRX pistoletas','TRX Pistol Squat','legs','trx','both','intermediate'),
  ('med-ball-slam','Kamuolio daužymas','Medicine Ball Slam','fullbody','ball','both','beginner'),
  ('wall-ball','Kamuolio metimas į sieną','Wall Ball','fullbody','ball','gym','intermediate'),
  ('med-ball-twist','Rusiškas sukimas su kamuoliu','Medicine Ball Russian Twist','core','ball','both','beginner'),
  ('hip-flexor-stretch','Klubų lenkiamųjų tempimas','Hip Flexor Stretch','mobility','bodyweight','home','beginner'),
  ('worlds-greatest-stretch','Geriausias pasaulyje tempimas','World''s Greatest Stretch','mobility','bodyweight','home','beginner'),
  ('thoracic-rotation','Krūtininės dalies sukimas','Thoracic Rotation','mobility','bodyweight','home','beginner'),
  ('couch-stretch','Sofos tempimas','Couch Stretch','mobility','bodyweight','home','intermediate'),
  ('cat-cow','Katė–karvė','Cat-Cow','mobility','bodyweight','home','beginner'),
  ('foam-roll-quads','Volavimas: keturgalviai','Foam Roll Quads','mobility','other','home','beginner')
) as v(slug, lt, en, mg, eq, loc, diff)
on conflict (slug) do update set
  name_lt = excluded.name_lt,
  name_en = excluded.name_en,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  location = excluded.location,
  difficulty = excluded.difficulty;
