/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedArRouteImport } from './routes/_authenticated/ar'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedCoachHistoryRouteImport } from './routes/_authenticated/coach-history'
import { Route as AuthenticatedFormRouteImport } from './routes/_authenticated/form'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMealPlanRouteImport } from './routes/_authenticated/meal-plan'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReadinessRouteImport } from './routes/_authenticated/readiness'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedSupplementsRouteImport } from './routes/_authenticated/supplements'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesSlugRouteImport } from './routes/exercises.$slug'
import { Route as AuthenticatedWorkoutDayRouteImport } from './routes/_authenticated/workout/$day'
import { Route as ApiPublicHealthIngestRouteImport } from './routes/api/public/health-ingest'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArRoute = AuthenticatedArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachHistoryRoute =
  AuthenticatedCoachHistoryRouteImport.update({
    id: '/coach-history',
    path: '/coach-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormRoute = AuthenticatedFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealPlanRoute = AuthenticatedMealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadinessRoute = AuthenticatedReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplementsRoute =
  AuthenticatedSupplementsRouteImport.update({
    id: '/supplements',
    path: '/supplements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesSlugRoute = ExercisesSlugRouteImport.update({
  id: '/exercises/$slug',
  path: '/exercises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutDayRoute = AuthenticatedWorkoutDayRouteImport.update({
  id: '/workout/$day',
  path: '/workout/$day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthIngestRoute = ApiPublicHealthIngestRouteImport.update({
  id: '/api/public/health-ingest',
  path: '/api/public/health-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/app': typeof AuthenticatedAppRoute
  '/ar': typeof AuthenticatedArRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/coach-history': typeof AuthenticatedCoachHistoryRoute
  '/form': typeof AuthenticatedFormRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/meal-plan': typeof AuthenticatedMealPlanRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/workout/$day': typeof AuthenticatedWorkoutDayRoute
  '/api/public/health-ingest': typeof ApiPublicHealthIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/app': typeof AuthenticatedAppRoute
  '/ar': typeof AuthenticatedArRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/coach-history': typeof AuthenticatedCoachHistoryRoute
  '/form': typeof AuthenticatedFormRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/me': typeof AuthenticatedMeRoute
  '/meal-plan': typeof AuthenticatedMealPlanRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/exercises': typeof ExercisesIndexRoute
  '/workout/$day': typeof AuthenticatedWorkoutDayRoute
  '/api/public/health-ingest': typeof ApiPublicHealthIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/ar': typeof AuthenticatedArRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/coach-history': typeof AuthenticatedCoachHistoryRoute
  '/_authenticated/form': typeof AuthenticatedFormRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/meal-plan': typeof AuthenticatedMealPlanRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/readiness': typeof AuthenticatedReadinessRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/supplements': typeof AuthenticatedSupplementsRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/exercises/$slug': typeof ExercisesSlugRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/_authenticated/workout/$day': typeof AuthenticatedWorkoutDayRoute
  '/api/public/health-ingest': typeof ApiPublicHealthIngestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/achievements'
    | '/app'
    | '/ar'
    | '/coach'
    | '/coach-history'
    | '/form'
    | '/history'
    | '/me'
    | '/meal-plan'
    | '/nutrition'
    | '/onboarding'
    | '/progress'
    | '/readiness'
    | '/reminders'
    | '/supplements'
    | '/training'
    | '/exercises/$slug'
    | '/exercises/'
    | '/workout/$day'
    | '/api/public/health-ingest'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/achievements'
    | '/app'
    | '/ar'
    | '/coach'
    | '/coach-history'
    | '/form'
    | '/history'
    | '/me'
    | '/meal-plan'
    | '/nutrition'
    | '/onboarding'
    | '/progress'
    | '/readiness'
    | '/reminders'
    | '/supplements'
    | '/training'
    | '/exercises/$slug'
    | '/exercises'
    | '/workout/$day'
    | '/api/public/health-ingest'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/achievements'
    | '/_authenticated/app'
    | '/_authenticated/ar'
    | '/_authenticated/coach'
    | '/_authenticated/coach-history'
    | '/_authenticated/form'
    | '/_authenticated/history'
    | '/_authenticated/me'
    | '/_authenticated/meal-plan'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/progress'
    | '/_authenticated/readiness'
    | '/_authenticated/reminders'
    | '/_authenticated/supplements'
    | '/_authenticated/training'
    | '/exercises/$slug'
    | '/exercises/'
    | '/_authenticated/workout/$day'
    | '/api/public/health-ingest'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ExercisesSlugRoute: typeof ExercisesSlugRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  ApiPublicHealthIngestRoute: typeof ApiPublicHealthIngestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ar': {
      id: '/_authenticated/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof AuthenticatedArRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach-history': {
      id: '/_authenticated/coach-history'
      path: '/coach-history'
      fullPath: '/coach-history'
      preLoaderRoute: typeof AuthenticatedCoachHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/form': {
      id: '/_authenticated/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof AuthenticatedFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meal-plan': {
      id: '/_authenticated/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof AuthenticatedMealPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/readiness': {
      id: '/_authenticated/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AuthenticatedReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplements': {
      id: '/_authenticated/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof AuthenticatedSupplementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$slug': {
      id: '/exercises/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof ExercisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout/$day': {
      id: '/_authenticated/workout/$day'
      path: '/workout/$day'
      fullPath: '/workout/$day'
      preLoaderRoute: typeof AuthenticatedWorkoutDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health-ingest': {
      id: '/api/public/health-ingest'
      path: '/api/public/health-ingest'
      fullPath: '/api/public/health-ingest'
      preLoaderRoute: typeof ApiPublicHealthIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedArRoute: typeof AuthenticatedArRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCoachHistoryRoute: typeof AuthenticatedCoachHistoryRoute
  AuthenticatedFormRoute: typeof AuthenticatedFormRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMealPlanRoute: typeof AuthenticatedMealPlanRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReadinessRoute: typeof AuthenticatedReadinessRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSupplementsRoute: typeof AuthenticatedSupplementsRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedWorkoutDayRoute: typeof AuthenticatedWorkoutDayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedArRoute: AuthenticatedArRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCoachHistoryRoute: AuthenticatedCoachHistoryRoute,
  AuthenticatedFormRoute: AuthenticatedFormRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMealPlanRoute: AuthenticatedMealPlanRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReadinessRoute: AuthenticatedReadinessRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSupplementsRoute: AuthenticatedSupplementsRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedWorkoutDayRoute: AuthenticatedWorkoutDayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ExercisesSlugRoute: ExercisesSlugRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  ApiPublicHealthIngestRoute: ApiPublicHealthIngestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
