insert into public.exercises (slug, name_lt, name_en, muscle_group, equipment, location, difficulty, instructions_lt, instructions_en, mistakes_lt, mistakes_en)
select v.slug, v.lt, v.en, v.mg, v.eq, v.loc, v.diff,
  'Pasiruošk „' || v.lt || '“: stabili padėtis, įtemptas liemuo. Leisk svorį kontroliuojamai 2–3 sek., dirbk pilna amplitude ir kvėpuok ritmiškai.',
  'Set up for the ' || v.en || ' with a stable stance and braced core. Lower under control for 2-3 seconds, work through the full range and keep your breathing rhythmic.',
  'Per didelis svoris, skubėjimas, per maža amplitudė ir prarasta liemens ar pečių padėtis.',
  'Too much load, rushed reps, a shortened range of motion and losing core or shoulder position.'
from (values
  ('front-squat','Priekinis pritūpimas','Front Squat','legs','barbell','gym','advanced'),
  ('box-squat','Pritūpimas ant dėžės','Box Squat','legs','barbell','gym','intermediate'),
  ('pause-squat','Pritūpimas su pauze','Paused Squat','legs','barbell','gym','intermediate'),
  ('zercher-squat','Zercher pritūpimas','Zercher Squat','legs','barbell','gym','advanced'),
  ('barbell-lunge','Išpuolis su štanga','Barbell Lunge','legs','barbell','gym','intermediate'),
  ('good-morning','Labas rytas','Good Morning','legs','barbell','gym','advanced'),
  ('barbell-step-up','Užlipimas su štanga','Barbell Step-Up','legs','barbell','gym','intermediate'),
  ('barbell-calf-raise','Blauzdų kėlimas su štanga','Barbell Calf Raise','legs','barbell','gym','beginner'),
  ('sumo-deadlift','Sumo mirties trauka','Sumo Deadlift','legs','barbell','gym','advanced'),
  ('db-bulgarian-split-squat','Bulgariškas pritūpimas su hanteliais','Dumbbell Bulgarian Split Squat','legs','dumbbell','both','intermediate'),
  ('db-step-up','Užlipimas su hanteliais','Dumbbell Step-Up','legs','dumbbell','both','beginner'),
  ('db-romanian-deadlift','Rumuniška trauka su hanteliais','Dumbbell Romanian Deadlift','legs','dumbbell','both','beginner'),
  ('db-sumo-squat','Sumo pritūpimas su hanteliu','Dumbbell Sumo Squat','legs','dumbbell','both','beginner'),
  ('db-walking-lunge','Einamieji išpuoliai su hanteliais','Dumbbell Walking Lunge','legs','dumbbell','both','intermediate'),
  ('db-calf-raise','Blauzdų kėlimas su hanteliais','Dumbbell Calf Raise','legs','dumbbell','both','beginner'),
  ('leg-extension','Kojų tiesimas treniruoklyje','Leg Extension','legs','machine','gym','beginner'),
  ('leg-curl','Kojų lenkimas treniruoklyje','Leg Curl','legs','machine','gym','beginner'),
  ('hack-squat','Hack pritūpimas','Hack Squat','legs','machine','gym','intermediate'),
  ('smith-squat','Pritūpimas Smith treniruoklyje','Smith Machine Squat','legs','machine','gym','beginner'),
  ('seated-calf-raise','Blauzdos sėdint treniruoklyje','Seated Calf Raise','legs','machine','gym','beginner'),
  ('abductor-machine','Šlaunų atitraukimas treniruoklyje','Hip Abductor Machine','legs','machine','gym','beginner'),
  ('adductor-machine','Šlaunų pritraukimas treniruoklyje','Hip Adductor Machine','legs','machine','gym','beginner'),
  ('bodyweight-squat','Pritūpimas be svorio','Bodyweight Squat','legs','bodyweight','home','beginner'),
  ('jump-squat','Šuoliukas iš pritūpimo','Jump Squat','legs','bodyweight','home','intermediate'),
  ('pistol-squat','Pistoletas','Pistol Squat','legs','bodyweight','home','advanced'),
  ('wall-sit','Sėdėjimas prie sienos','Wall Sit','legs','bodyweight','home','beginner'),
  ('reverse-lunge','Išpuolis atgal','Reverse Lunge','legs','bodyweight','home','beginner'),
  ('cossack-squat','Kazokiškas pritūpimas','Cossack Squat','legs','bodyweight','home','intermediate'),
  ('calf-raise','Stovimas blauzdų kėlimas','Standing Calf Raise','legs','bodyweight','home','beginner'),
  ('band-squat','Pritūpimas su guma','Band Squat','legs','band','home','beginner'),
  ('band-lateral-walk','Ėjimas į šoną su guma','Band Lateral Walk','glutes','band','home','beginner'),
  ('band-leg-curl','Kojų lenkimas su guma','Band Leg Curl','legs','band','home','beginner'),
  ('band-glute-kickback','Kojos spyris atgal su guma','Band Glute Kickback','glutes','band','home','beginner'),
  ('kb-front-rack-squat','Pritūpimas su svarsčiais ant krūtinės','Kettlebell Front Rack Squat','legs','kettlebell','both','intermediate'),
  ('kb-lunge','Išpuolis su svarsčiu','Kettlebell Lunge','legs','kettlebell','both','beginner'),
  ('kb-deadlift','Svarsčio mirties trauka','Kettlebell Deadlift','legs','kettlebell','both','beginner'),
  ('incline-bench-press','Spaudimas nuo įstrižo suolo','Incline Bench Press','chest','barbell','gym','intermediate'),
  ('decline-bench-press','Spaudimas nuo nuožulnaus suolo','Decline Bench Press','chest','barbell','gym','intermediate'),
  ('close-grip-bench-press','Spaudimas siauru griebimu','Close-Grip Bench Press','arms','barbell','gym','intermediate'),
  ('db-incline-press','Įstrižas spaudimas su hanteliais','Incline Dumbbell Press','chest','dumbbell','both','beginner'),
  ('db-fly','Hantelių išskėtimas','Dumbbell Fly','chest','dumbbell','both','beginner'),
  ('db-pullover','Hantelio kėlimas per galvą','Dumbbell Pullover','chest','dumbbell','both','intermediate'),
  ('cable-fly','Kryžminis suvedimas trosuose','Cable Fly','chest','cable','gym','beginner'),
  ('cable-crossover','Kryžminis trosų suvedimas žemyn','Cable Crossover','chest','cable','gym','intermediate'),
  ('pec-deck','Krūtinės suvedimas treniruoklyje','Pec Deck','chest','machine','gym','beginner'),
  ('chest-press-machine','Krūtinės spaudimas treniruoklyje','Chest Press Machine','chest','machine','gym','beginner'),
  ('chest-dip','Atsispaudimas ant lygiagrečių','Chest Dip','chest','pullup_bar','both','intermediate'),
  ('wide-push-up','Platus atsispaudimas','Wide Push-Up','chest','bodyweight','home','beginner'),
  ('diamond-push-up','Deimantinis atsispaudimas','Diamond Push-Up','arms','bodyweight','home','intermediate'),
  ('decline-push-up','Atsispaudimas su pakeltomis kojomis','Decline Push-Up','chest','bodyweight','home','intermediate'),
  ('archer-push-up','Šaulio atsispaudimas','Archer Push-Up','chest','bodyweight','home','advanced'),
  ('band-chest-press','Krūtinės spaudimas su guma','Band Chest Press','chest','band','home','beginner'),
  ('pendlay-row','Pendlay irklavimas','Pendlay Row','back','barbell','gym','advanced'),
  ('t-bar-row','T formos irklavimas','T-Bar Row','back','barbell','gym','intermediate'),
  ('rack-pull','Trauka nuo stovų','Rack Pull','back','barbell','gym','intermediate'),
  ('barbell-shrug','Pečių gūžčiojimas su štanga','Barbell Shrug','back','barbell','gym','beginner'),
  ('one-arm-db-row','Vienos rankos irklavimas su hanteliu','One-Arm Dumbbell Row','back','dumbbell','both','beginner'),
  ('chest-supported-row','Irklavimas gulint ant suolo','Chest-Supported Row','back','dumbbell','gym','beginner'),
  ('db-shrug','Pečių gūžčiojimas su hanteliais','Dumbbell Shrug','back','dumbbell','both','beginner'),
  ('seated-cable-row','Irklavimas trosu sėdint','Seated Cable Row','back','cable','gym','beginner'),
  ('straight-arm-pulldown','Tiesių rankų trauka žemyn','Straight-Arm Pulldown','back','cable','gym','beginner'),
  ('wide-grip-pulldown','Plati trauka prie krūtinės','Wide-Grip Lat Pulldown','back','machine','gym','beginner'),
  ('close-grip-pulldown','Siaura trauka prie krūtinės','Close-Grip Pulldown','back','machine','gym','beginner'),
  ('machine-row','Irklavimas treniruoklyje','Machine Row','back','machine','gym','beginner'),
  ('hyperextension','Nugaros tiesimas','Back Extension','back','machine','gym','beginner'),
  ('chin-up','Prisitraukimas atvirkštiniu griebimu','Chin-Up','back','pullup_bar','both','intermediate'),
  ('neutral-grip-pull-up','Prisitraukimas neutraliu griebimu','Neutral-Grip Pull-Up','back','pullup_bar','both','intermediate'),
  ('inverted-row','Australiškas prisitraukimas','Inverted Row','back','pullup_bar','both','beginner'),
  ('dead-hang','Kabėjimas ant skersinio','Dead Hang','back','pullup_bar','both','beginner'),
  ('band-pulldown','Trauka žemyn su guma','Band Pulldown','back','band','home','beginner'),
  ('superman','Supermenas','Superman','back','bodyweight','home','beginner'),
  ('db-shoulder-press','Pečių spaudimas su hanteliais','Dumbbell Shoulder Press','shoulders','dumbbell','both','beginner'),
  ('arnold-press','Arnoldo spaudimas','Arnold Press','shoulders','dumbbell','both','intermediate'),
  ('lateral-raise','Rankų kėlimas į šonus','Lateral Raise','shoulders','dumbbell','both','beginner'),
  ('front-raise','Rankų kėlimas į priekį','Front Raise','shoulders','dumbbell','both','beginner'),
  ('rear-delt-fly','Užpakalinių deltų išskėtimas','Rear Delt Fly','shoulders','dumbbell','both','beginner'),
  ('cable-lateral-raise','Kėlimas į šoną trosu','Cable Lateral Raise','shoulders','cable','gym','intermediate'),
  ('upright-row','Trauka prie smakro','Upright Row','shoulders','barbell','gym','intermediate'),
  ('landmine-press','Landmine spaudimas','Landmine Press','shoulders','barbell','gym','intermediate'),
  ('shoulder-press-machine','Pečių spaudimas treniruoklyje','Shoulder Press Machine','shoulders','machine','gym','beginner'),
  ('band-pull-apart','Gumos ištempimas prieš krūtinę','Band Pull-Apart','shoulders','band','home','beginner'),
  ('pike-push-up','Atsispaudimas kampu','Pike Push-Up','shoulders','bodyweight','home','intermediate'),
  ('handstand-hold','Stovėjimas ant rankų prie sienos','Wall Handstand Hold','shoulders','bodyweight','home','advanced'),
  ('barbell-curl','Bicepso lenkimas su štanga','Barbell Curl','arms','barbell','gym','beginner'),
  ('ez-bar-curl','Lenkimas su EZ štanga','EZ-Bar Curl','arms','barbell','gym','beginner'),
  ('skullcrusher','Tricepso tiesimas gulint','Skullcrusher','arms','barbell','gym','intermediate'),
  ('hammer-curl','Plaktukinis lenkimas','Hammer Curl','arms','dumbbell','both','beginner'),
  ('incline-db-curl','Lenkimas ant įstrižo suolo','Incline Dumbbell Curl','arms','dumbbell','gym','intermediate'),
  ('concentration-curl','Koncentruotas lenkimas','Concentration Curl','arms','dumbbell','both','beginner'),
  ('overhead-triceps-extension','Tricepso tiesimas virš galvos','Overhead Triceps Extension','arms','dumbbell','both','beginner'),
  ('wrist-curl','Riešų lenkimas','Wrist Curl','arms','dumbbell','both','beginner'),
  ('preacher-curl','Lenkimas ant pulto','Preacher Curl','arms','machine','gym','beginner'),
  ('cable-curl','Bicepso lenkimas trosu','Cable Curl','arms','cable','gym','beginner'),
  ('triceps-pushdown','Tricepso spaudimas žemyn','Triceps Pushdown','arms','cable','gym','beginner'),
  ('rope-pushdown','Tricepso spaudimas su virve','Rope Pushdown','arms','cable','gym','beginner'),
  ('bench-dip','Atsispaudimas nuo suolo','Bench Dip','arms','bodyweight','home','beginner'),
  ('close-grip-push-up','Siauras atsispaudimas','Close-Grip Push-Up','arms','bodyweight','home','beginner'),
  ('band-curl','Bicepso lenkimas su guma','Band Curl','arms','band','home','beginner'),
  ('band-triceps-extension','Tricepso tiesimas su guma','Band Triceps Extension','arms','band','home','beginner'),
  ('farmers-carry','Ūkininko nešimas','Farmer''s Carry','fullbody','dumbbell','both','beginner'),
  ('hanging-leg-raise','Kojų kėlimas kabant','Hanging Leg Raise','abs','pullup_bar','both','advanced'),
  ('toes-to-bar','Kojų kėlimas prie skersinio','Toes to Bar','abs','pullup_bar','both','advanced'),
  ('captains-chair-raise','Kelių kėlimas kapitono kėdėje','Captain''s Chair Knee Raise','abs','machine','gym','intermediate'),
  ('cable-crunch','Presas trosu klūpant','Cable Crunch','abs','cable','gym','intermediate'),
  ('pallof-press','Pallof spaudimas','Pallof Press','core','cable','gym','intermediate'),
  ('ab-wheel','Ratukas presui','Ab Wheel Rollout','abs','other','home','advanced'),
  ('bicycle-crunch','Dviratukas','Bicycle Crunch','abs','bodyweight','home','beginner'),
  ('side-plank','Šoninė lenta','Side Plank','core','bodyweight','home','beginner'),
  ('hollow-hold','Laivelis','Hollow Hold','core','bodyweight','home','intermediate'),
  ('dead-bug','Negyvas vabalas','Dead Bug','core','bodyweight','home','beginner'),
  ('bird-dog','Paukštis-šuo','Bird Dog','core','bodyweight','home','beginner'),
  ('v-up','V formos kėlimas','V-Up','abs','bodyweight','home','intermediate'),
  ('sit-up','Atsilenkimas','Sit-Up','abs','bodyweight','home','beginner'),
  ('plank-shoulder-tap','Lenta su pečių palietimu','Plank Shoulder Tap','core','bodyweight','home','beginner'),
  ('dragon-flag','Drakono vėliava','Dragon Flag','abs','bodyweight','home','advanced'),
  ('db-hip-thrust','Dubens kėlimas su hanteliu','Dumbbell Hip Thrust','glutes','dumbbell','both','beginner'),
  ('cable-kickback','Kojos spyris trosu','Cable Kickback','glutes','cable','gym','beginner'),
  ('band-hip-thrust','Dubens kėlimas su guma','Band Hip Thrust','glutes','band','home','beginner'),
  ('single-leg-glute-bridge','Tiltelis ant vienos kojos','Single-Leg Glute Bridge','glutes','bodyweight','home','intermediate'),
  ('frog-pump','Varlės kėlimai','Frog Pump','glutes','bodyweight','home','beginner'),
  ('glute-machine','Sėdmenų treniruoklis','Glute Kickback Machine','glutes','machine','gym','beginner'),
  ('rowing-machine','Irklavimo treniruoklis','Rowing Machine','cardio','cardio','gym','beginner'),
  ('assault-bike','Oro dviratis','Assault Bike','cardio','cardio','gym','intermediate'),
  ('treadmill-sprint','Sprintas bėgtakyje','Treadmill Sprint','cardio','cardio','gym','intermediate'),
  ('stair-climber','Laiptų treniruoklis','Stair Climber','cardio','cardio','gym','beginner'),
  ('elliptical','Elipsinis treniruoklis','Elliptical Trainer','cardio','cardio','gym','beginner'),
  ('ski-erg','SkiErg','Ski Erg','cardio','cardio','gym','intermediate'),
  ('box-jump','Šuolis ant dėžės','Box Jump','cardio','bodyweight','both','intermediate'),
  ('high-knees','Aukšti keliai','High Knees','cardio','bodyweight','home','beginner'),
  ('jumping-jack','Šuoliukai su rankomis','Jumping Jack','cardio','bodyweight','home','beginner'),
  ('bear-crawl','Meškos ėjimas','Bear Crawl','fullbody','bodyweight','home','intermediate'),
  ('battle-ropes','Kovos virvės','Battle Ropes','cardio','other','gym','intermediate'),
  ('sled-push','Rogių stūmimas','Sled Push','fullbody','other','gym','intermediate'),
  ('thruster','Trasteris','Thruster','fullbody','barbell','gym','advanced'),
  ('clean-and-press','Ėmimas ir spaudimas','Clean and Press','fullbody','barbell','gym','advanced'),
  ('kb-clean','Svarsčio ėmimas','Kettlebell Clean','fullbody','kettlebell','both','intermediate'),
  ('kb-snatch','Svarsčio trūktelėjimas','Kettlebell Snatch','fullbody','kettlebell','both','advanced'),
  ('kb-turkish-get-up','Turkiškas atsikėlimas','Turkish Get-Up','fullbody','kettlebell','both','advanced'),
  ('trx-row','TRX irklavimas','TRX Row','back','trx','both','beginner'),
  ('trx-push-up','TRX atsispaudimas','TRX Push-Up','chest','trx','both','intermediate'),
  ('trx-fallout','TRX liemens kritimas','TRX Fallout','core','trx','both','advanced'),
  ('trx-pistol','TRX pistoletas','TRX Pistol Squat','legs','trx','both','intermediate'),
  ('med-ball-slam','Kamuolio daužymas','Medicine Ball Slam','fullbody','ball','both','beginner'),
  ('wall-ball','Kamuolio metimas į sieną','Wall Ball','fullbody','ball','gym','intermediate'),
  ('med-ball-twist','Rusiškas sukimas su kamuoliu','Medicine Ball Russian Twist','core','ball','both','beginner'),
  ('hip-flexor-stretch','Klubų lenkiamųjų tempimas','Hip Flexor Stretch','mobility','bodyweight','home','beginner'),
  ('worlds-greatest-stretch','Geriausias pasaulyje tempimas','World''s Greatest Stretch','mobility','bodyweight','home','beginner'),
  ('thoracic-rotation','Krūtininės dalies sukimas','Thoracic Rotation','mobility','bodyweight','home','beginner'),
  ('couch-stretch','Sofos tempimas','Couch Stretch','mobility','bodyweight','home','intermediate'),
  ('cat-cow','Katė–karvė','Cat-Cow','mobility','bodyweight','home','beginner'),
  ('foam-roll-quads','Volavimas: keturgalviai','Foam Roll Quads','mobility','other','home','beginner')
) as v(slug, lt, en, mg, eq, loc, diff)
on conflict (slug) do update set
  name_lt = excluded.name_lt,
  name_en = excluded.name_en,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  location = excluded.location,
  difficulty = excluded.difficulty;